/* ═══════════════════════════════════════════════
   SOPHTMADE — PRODUCT DATA
═══════════════════════════════════════════════ */

const PRODUCTS = [
  {
    id: 1,
    name: "Manchester United Home Jersey",
    club: "Manchester United",
    category: "club",
    version: "fan",
    kit: "home",
    price: 20000,
    description: "The iconic red of Old Trafford. This Fan version home kit features Manchester United's classic crest and bold red colourway. Breathable polyester fabric, perfect for matchdays and everyday wear.",
    image: "images/jerseys/man-utd-home-fan.jpg",
    rating: 5,
    reviewCount: 14,
    sizes: ["S","M","L","XL","XXL"],
    featured: true
  },
  {
    id: 2,
    name: "Manchester United Home Jersey",
    club: "Manchester United",
    category: "club",
    version: "player",
    kit: "home",
    price: 25000,
    description: "The authentic Player edition of Man United's home kit. Same high-performance fabric worn by the players — lightweight, quick-dry, and tailored fit.",
    image: "images/jerseys/man-utd-home-fan.jpg",
    rating: 5,
    reviewCount: 8,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 3,
    name: "Manchester United Away Jersey",
    club: "Manchester United",
    category: "club",
    version: "fan",
    kit: "away",
    price: 20000,
    description: "United's away strip in a fresh colourway. Fan edition — ideal for away days and casual wear. Features the club crest and sponsor badge.",
    image: "images/jerseys/man-utd-away-fan.jpg",
    rating: 4,
    reviewCount: 6,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 4,
    name: "Real Madrid Away Jersey",
    club: "Real Madrid",
    category: "club",
    version: "player",
    kit: "away",
    price: 25000,
    description: "Los Blancos' Player edition away kit. The same jersey worn by the first team — advanced Dri-Fit technology, precision-cut, with the iconic Real Madrid crest.",
    image: "images/jerseys/real-madrid-away-player.jpg",
    rating: 5,
    reviewCount: 22,
    sizes: ["S","M","L","XL","XXL"],
    featured: true
  },
  {
    id: 5,
    name: "Real Madrid Home Jersey",
    club: "Real Madrid",
    category: "club",
    version: "fan",
    kit: "home",
    price: 20000,
    description: "The classic white of the Bernabeu. Fan edition of Real Madrid's home kit — clean, premium design with the golden badge.",
    image: "images/jerseys/real-madrid-home-fan.jpg",
    rating: 5,
    reviewCount: 18,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 6,
    name: "Chelsea FC Home Jersey",
    club: "Chelsea",
    category: "club",
    version: "fan",
    kit: "home",
    price: 20000,
    description: "The famous Chelsea blue. Fan edition home kit with the iconic lion crest. Comfortable polyester blend, great for the stadium or the street.",
    image: "images/jerseys/chelsea-home-fan.jpg",
    rating: 4,
    reviewCount: 9,
    sizes: ["S","M","L","XL","XXL"],
    featured: true
  },
  {
    id: 7,
    name: "Chelsea FC Away Jersey",
    club: "Chelsea",
    category: "club",
    version: "player",
    kit: "away",
    price: 25000,
    description: "Chelsea's Player edition away kit. Authentic match-spec jersey in a striking colourway — the same quality as what the squad wears at Stamford Bridge.",
    image: "images/jerseys/chelsea-away-player.jpg",
    rating: 5,
    reviewCount: 5,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 8,
    name: "FC Barcelona Home Jersey",
    club: "Barcelona",
    category: "club",
    version: "player",
    kit: "home",
    price: 25000,
    description: "The famous Blaugrana stripes. Player edition of Barca's iconic home kit — elite-grade fabric, precision stitching, and the Catalan crest worn with pride.",
    image: "images/jerseys/barcelona-home-player.jpg",
    rating: 5,
    reviewCount: 31,
    sizes: ["S","M","L","XL","XXL"],
    featured: true
  },
  {
    id: 9,
    name: "FC Barcelona Away Jersey",
    club: "Barcelona",
    category: "club",
    version: "fan",
    kit: "away",
    price: 20000,
    description: "Barca's away colours in Fan edition. Clean design with the full Barcelona crest and sponsor badge. Stand out from the crowd.",
    image: "images/jerseys/barcelona-away-fan.jpg",
    rating: 4,
    reviewCount: 7,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 10,
    name: "PSG Away Jersey",
    club: "PSG",
    category: "club",
    version: "fan",
    kit: "away",
    price: 20000,
    description: "Paris Saint-Germain's away strip. Fan edition in a clean, modern colourway. Features the Eiffel Tower crest and all-over print detail.",
    image: "images/jerseys/psg-away-fan.jpg",
    rating: 5,
    reviewCount: 12,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 11,
    name: "PSG Home Jersey",
    club: "PSG",
    category: "club",
    version: "player",
    kit: "home",
    price: 25000,
    description: "The deep navy of the Parc des Princes. Player edition home kit — the authentic match jersey with the iconic red and blue sash design.",
    image: "images/jerseys/psg-home-player.jpg",
    rating: 5,
    reviewCount: 10,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 12,
    name: "Arsenal Away Jersey",
    club: "Arsenal",
    category: "club",
    version: "fan",
    kit: "away",
    price: 20000,
    description: "The Gunners' away kit in Fan edition. Arsenal's clean away design with the cannon crest. Great quality at an accessible price.",
    image: "images/jerseys/arsenal-away-fan.jpg",
    rating: 4,
    reviewCount: 4,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 13,
    name: "Arsenal Home Jersey",
    club: "Arsenal",
    category: "club",
    version: "player",
    kit: "home",
    price: 24500,
    description: "Emirates red. Arsenal's Player edition home kit — the same spec worn by the squad at the Emirates Stadium.",
    image: "images/jerseys/arsenal-home-player.jpg",
    rating: 5,
    reviewCount: 6,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 14,
    name: "Liverpool Home Jersey",
    club: "Liverpool",
    category: "club",
    version: "fan",
    kit: "home",
    price: 20000,
    description: "All red kit, White Nike swoosh and Standard Chartered Sponsor. LFC crest on the left, clean, simple, iconic Anfield look.",
    image: "images/jerseys/liverpool-home-fan.jpg",
    rating: 5,
    reviewCount: 7,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 15,
    name: "Liverpool Away Jersey",
    club: "Liverpool",
    category: "club",
    version: "player",
    kit: "away",
    price: 25000,
    description: "White base with teal and lime green accents. LFC crest, clean, modern contrast to the all-red home.",
    image: "images/jerseys/liverpool-away-player.jpg",
    rating: 5,
    reviewCount: 8,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 16,
    name: "Atletico Madrid Away Jersey",
    club: "Atletico Madrid",
    category: "club",
    version: "player",
    kit: "away",
    price: 25000,
    description: "Black base with dark grey/teal geometric pattern. Teal Nike swoosh and Riyadh Air sponsor in white/teal.",
    image: "images/jerseys/athletico-away-player.jpg",
    rating: 5,
    reviewCount: 8,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 17,
    name: "Atletico Madrid Home Jersey",
    club: "Atletico Madrid",
    category: "club",
    version: "fan",
    kit: "home",
    price: 20000,
    description: "Red and white vertical stripes all over. Blue Nike swoosh and Nike logo. Main sponsor Riyadh Air in white across chest. Blue trim on collar and sleeves.",
    image: "images/jerseys/athletico-home-fan.jpg",
    rating: 5,
    reviewCount: 5,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 18,
    name: "Manchester City Home Jersey",
    club: "Manchester City",
    category: "club",
    version: "fan",
    kit: "home",
    price: 20000,
    description: "Sky blue shirt all over. Navy blue Nike swoosh + Etihad Airways Sponsor in white. Navy trim on collar + sleeves.",
    image: "images/jerseys/Manchestercity-home-fan.jpg",
    rating: 5,
    reviewCount: 20,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 19,
    name: "Manchester City Away Jersey",
    club: "Manchester City",
    category: "club",
    version: "player",
    kit: "away",
    price: 25000,
    description: "White base with Abstract light-blue + silver geometricpattern across the body. Silver Nike Swoosh + Ethihad sponsor in navy.",
    image: "images/jerseys/manchestercity-away-player.jpg",
    rating: 5,
    reviewCount: 22,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 20,
    name: "Nigeria Home Jersey",
    club: "Nigeria",
    category: "national",
    version: "fan",
    kit: "home",
    price: 20000,
    description: "The Super Eagles' iconic green-and-white home kit. Fan edition — one of the most celebrated national team jerseys in Africa. Represent Nigeria with pride.",
    image: "images/jerseys/nigeria-home-fan.jpg",
    rating: 5,
    reviewCount: 41,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 21,
    name: "Nigeria Away Jersey",
    club: "Nigeria",
    category: "national",
    version: "fan",
    kit: "away",
    price: 20000,
    description: "The Super Eagles away strip. Fan edition in a bold colourway. Nigeria's away kit is always a fan favourite — don't miss out.",
    image: "images/jerseys/nigeria-away-fan.jpg",
    rating: 5,
    reviewCount: 28,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
  {
    id: 22,
    name: "Brazil Home Jersey",
    club: "Brazil",
    category: "national",
    version: "fan",
    kit: "home",
    price: 20000,
    description: "The iconic Seleção yellow. Brazil's home kit in Fan edition — the most celebrated football shirt in the world, now in your wardrobe.",
    image: "images/jerseys/brazil-home-fan.jpg",
    rating: 5,
    reviewCount: 35,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  },
   {
    id: 23,
    name: "Brazil Home Jersey",
    club: "Brazil",
    category: "national",
    version: "player",
    kit: "home",
    price: 25000,
    description: "The iconic Seleção yellow. Brazil's home kit in Fan edition — the most celebrated football shirt in the world, now in your wardrobe.",
    image: "images/jerseys/brazil-home-fan.jpg",
    rating: 5,
    reviewCount: 35,
    sizes: ["S","M","L","XL","XXL"],
    featured: false
  }
];

/* ─── Helper: format price as ₦ ─────────────── */
function formatPrice(amount) {
  return '₦' + amount.toLocaleString('en-NG');
}

/* ─── Helper: render star rating ────────────── */
function renderStars(rating, reviewCount) {
  const full  = Math.floor(rating);
  const half  = rating % 1 >= 0.5 ? 1 : 0;
  const empty = 5 - full - half;
  const stars = '★'.repeat(full) + (half ? '½' : '') + '☆'.repeat(empty);
  return `<span class="stars">${stars}</span><span class="stars__count">(${reviewCount})</span>`;
}

/* ─── Helper: get unique clubs ───────────────── */
function getUniqueClubs() {
  const clubs = [...new Set(PRODUCTS.map(p => p.club))];
  return clubs.sort();
}